### PR TITLE
use decimal for better precision

### PR DESCRIPTION
**Pull request by PsychicCat**
Great tool, I found the conversion rates could be off by a small amount due to the floating point precision. Very small amount, but it can add up. Using Decimal is more accurate for money.

### CODE REVIEW

**Comment by TheButterZone** [comment]
As we approach $10k USD, I was thinking of submitting an issue or even trying to re-code the decimal places further out than 4. Not sure if should go to 6 to cover tens & hundredths of cents, or all the way to 8, or certainly beyond my capability- making it a variable in the URL to specify which decimal place to be the last one, and rounded up to.

@fordhurley

**Comment by TheButterZone** [comment]
As we approach $10k USD, I was thinking of submitting an issue or even trying to re-code the decimal places further out than 4. Not sure if should go to 6 to cover tens & hundredths of cents, or all the way to 8, or certainly beyond my capability- making it a variable in the URL to specify which decimal place to be the last one, and rounded up to.

@ford

**Comment by TheButterZone** [comment]
So @PsychicCat did my merged PR mess up your Decimal PR or can it still work?

After I linked to it in Freenode #python on Nov 27:

15:25:37 stealth_: TBZ1, https://docs.python.org/3/library/decimal.html
15:27:29 stealth_: TBZ1, who uses float for currency?
15:28:04 stealth_: TBZ1, that comment is valid you should use the decimal visit that link

**Comment by fordhurley** [comment]
I find it very unlikely that this would make any difference at the precision we're using. Decimal is crucial for accounting applications because the errors can build up, but in this case the losses in precision are constrained to very few operations. For showing the BTC value of 10 USD with 11762.19 USD / BTC, the difference between using float or Decimal will be tiny. 

```
0.0008501818113803637 <- using float
0.0008501818113803636907752722920 <- using Decimal
```

**Pull request closed without merging**
